Repository newrelic/newrelic-java-agent, pull requests merged in 2022-03, with the labels that each got.

#707 BlockingQueue and guard adding null
  functional_test/src/test/java/test/newrelic/test/agent/api/ApiTest.java
  instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorStatsService.java
  newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
  newrelic-agent/src/main/java/com/newrelic/agent/AsyncApiImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/HarvestServiceImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/Harvestable.java
  newrelic-agent/src/main/java/com/newrelic/agent/TokenImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java
  newrelic-agent/src/main/java/com/newrelic/agent/TransactionService.java
  newrelic-agent/src/main/java/com/newrelic/agent/database/DatastoreMetrics.java
  newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/PointCutClassTransformer.java
  newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/FinalClassTransformer.java
  newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationClassTransformer.java
  newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/AgentWeaverListener.java
  newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/ClassWeaverService.java
  newrelic-agent/src/main/java/com/newrelic/agent/jmx/LinkingMetadataRegistration.java
  newrelic-agent/src/main/java/com/newrelic/agent/language/SourceLibraryDetector.java
  newrelic-agent/src/main/java/com/newrelic/agent/profile/v2/TransactionProfile.java
  newrelic-agent/src/main/java/com/newrelic/agent/rpm/RPMConnectionServiceImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/samplers/SamplerServiceImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/service/ServiceManagerImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/service/StatsServiceMetricAggregator.java
  newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/InsightsServiceImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventsServiceImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/TransactionEventsService.java
  newrelic-agent/src/main/java/com/newrelic/agent/stats/StatsService.java
  newrelic-agent/src/main/java/com/newrelic/agent/stats/StatsServiceImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/threads/ThreadStateSampler.java
  newrelic-agent/src/main/java/com/newrelic/agent/transport/DataSenderImpl.java
  newrelic-agent/src/main/java/com/newrelic/agent/transport/apache/ApacheHttpClientWrapper.java
  newrelic-agent/src/main/java/com/newrelic/agent/utilization/CloudUtility.java
  newrelic-agent/src/test/java/com/newrelic/agent/HarvestServiceTest.java
  newrelic-agent/src/test/java/com/newrelic/agent/language/SourceLibraryDetectorTest.java
  newrelic-agent/src/test/java/com/newrelic/agent/stats/StatsServiceTest.java
  newrelic-agent/src/test/java/com/newrelic/agent/utilization/CloudUtilityTest.java
Labels: GTSE, Q4 SC, 7.6.0

#768 add tests for logging config
  newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigImplTest.java
Labels: testing, 7.6.0

#774 Logging config impl tests (ApplicationLoggingConfigImpl)
  newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingConfigImplTest.java
Labels: testing, 7.6.0

#776 log forwarding tests (ApplicationLoggingForwardingConfigImpl)
  newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingForwardingConfigTest.java
Labels: testing, 7.6.0

#778 add logging metric tests (ApplicationLoggingMetricsConfig)
  newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingMetricsConfigTest.java
Labels: testing, 7.6.0

#777 local decorating config tests added (ApplicationLoggingLocalDecoratingConfig)
  newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingLocalDecoratingConfigTest.java
Labels: testing, 7.6.0

#804 Clarify how and why maxSamplesStored is being set to 0 by the collector
  newrelic-agent/src/main/java/com/newrelic/agent/HarvestServiceImpl.java
Labels: 7.6.0

#786 Include AIT logging test in AIT basic features AIT workflow
  .github/workflows/AITs-Basic-Features.yml
Labels: 7.6.0
